# Site settings
title: Analog Rocks.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://analog.rocks" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /episodes/:year-:month-:day.html