# Site settings
title: Analog Rocks.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://analog.rocks" # the base hostname & protocol for your site
desc: "模拟摇滚是一个播客节目。这个节目的主持人都是坏人。"

# Build settings
markdown: kramdown
permalink: /episodes/:year-:month-:day.html

sass:
    style: :compressed
